CREATE TABLE IF NOT EXISTS agentgo_schema_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name VARCHAR(100) NOT NULL,
    initialized_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO agentgo_schema_metadata (schema_name)
SELECT 'agentgo'
WHERE NOT EXISTS (
    SELECT 1
    FROM agentgo_schema_metadata
    WHERE schema_name = 'agentgo'
);
